feat(ExecCommand): add Logging feature
Hazmi35/discordbot-template-legacy pull request #225
Opened 2021-08-21 06:23 UTC by Mednoob

Demonstration:

![LoggingDemonstration](https://cdn.discordapp.com/attachments/564458704213114905/878523447263780874/S8PnM6lOM8.gif)

2021-08-22 03:46 UTC, Hazmi35 commented
What's the difference with the regular exec command?

2021-08-23 05:00 UTC, Mednoob commented
> What's the difference with the regular exec command?

If you use pm2, there's a command `pm2 logs` right? Using the regular exec command won't give the result since `pm2 logs` will end only if it is `ctrl + c`'d or by closing the terminal. But, with the logs option, it will show the result when the pm2 logs give outputs. Because, the logs option creates new process and then send output to discord whenever the process gets an output.

Here's the demonstration:
![PM2Demonstration](https://cdn.discordapp.com/attachments/564458704213114905/879227886203207731/ORNJAXsp9v.gif)

2021-08-23 05:34 UTC, Hazmi35 commented
Is there a way to terminate the logs instance? Showing it's PID and using exec to run `kill <pid> -s 0` is doable, but isn't it better to implement a way to terminate it?

2021-08-23 07:12 UTC, Mednoob commented
> Is there a way to terminate the logs instance? Showing it's PID and using exec to run `kill <pid> -s 0` is doable, but isn't it better to implement a way to terminate it?

Yes, and that's what I'm currently thinking about.

Of course, it will use caching system to cache the spawned process. I'm thinking of these ways to end the process:
1. Show its PID and then create an option named `terminate` or something.
2. Like number 1, but with simpler custom ID instead.
3. Create an option named `kill-all` or `terminate-all` to kill **all** the process spawned by the bot instantly.
4. Create some options on the process spawn message using reaction or interaction collector

Or maybe you have any better or simpler idea?

2021-08-23 07:25 UTC, Hazmi35 commented
> > Is there a way to terminate the logs instance? Showing it's PID and using exec to run `kill <pid> -s 0` is doable, but isn't it better to implement a way to terminate it?
> 
> Yes, and that's what I'm currently thinking about.
> 
> Of course, it will use caching system to cache the spawned process. I'm thinking of these ways to end the process:
> 
> 1. Show its PID and then create an option named `terminate` or something.
> 2. Like number 1, but with simpler custom ID instead.
> 3. Create an option named `kill-all` or `terminate-all` to kill **all** the process spawned by the bot instantly.
> 4. Create some options on the process spawn message using reaction or interaction collector
> 
> Or maybe you have any better or simpler idea?

Come to think of it, shouldn't this be a separate command? SpawnCommand for example
With that we could create something like `$spawn create <name> <shell command>` and `$spawn terminate <name>`
Then, we can store the ChildProcess with the name as the key, and then we can use ChildProcess#kill to terminate it.

2021-08-23 07:33 UTC, Hazmi35 commented
> > > Is there a way to terminate the logs instance? Showing it's PID and using exec to run `kill <pid> -s 0` is doable, but isn't it better to implement a way to terminate it?
> > 
> > 
> > Yes, and that's what I'm currently thinking about.
> > Of course, it will use caching system to cache the spawned process. I'm thinking of these ways to end the process:
> > 
> > 1. Show its PID and then create an option named `terminate` or something.
> > 2. Like number 1, but with simpler custom ID instead.
> > 3. Create an option named `kill-all` or `terminate-all` to kill **all** the process spawned by the bot instantly.
> > 4. Create some options on the process spawn message using reaction or interaction collector
> > 
> > Or maybe you have any better or simpler idea?
> 
> Come to think of it, shouldn't this be a separate command? SpawnCommand for example
> With that we could create something like `$spawn create <name> <shell command>` and `$spawn terminate <name>`
> Then, we can store the ChildProcess with the name as the key, and then we can use ChildProcess#kill to terminate it.

This way, it wouldn't interfere with ExecCommand, for example. This functionality blocks user who wants to run "logs --name App" from the ExecCommand.

So I think it's best to separate them from ExecCommand

2021-08-23 09:09 UTC, Mednoob commented
> > > > Is there a way to terminate the logs instance? Showing it's PID and using exec to run `kill <pid> -s 0` is doable, but isn't it better to implement a way to terminate it?
> > > 
> > > 
> > > Yes, and that's what I'm currently thinking about.
> > > Of course, it will use caching system to cache the spawned process. I'm thinking of these ways to end the process:
> > > 
> > > 1. Show its PID and then create an option named `terminate` or something.
> > > 2. Like number 1, but with simpler custom ID instead.
> > > 3. Create an option named `kill-all` or `terminate-all` to kill **all** the process spawned by the bot instantly.
> > > 4. Create some options on the process spawn message using reaction or interaction collector
> > > 
> > > Or maybe you have any better or simpler idea?
> > 
> > 
> > Come to think of it, shouldn't this be a separate command? SpawnCommand for example
> > With that we could create something like `$spawn create <name> <shell command>` and `$spawn terminate <name>`
> > Then, we can store the ChildProcess with the name as the key, and then we can use ChildProcess#kill to terminate it.
> 
> This way, it wouldn't interfere with ExecCommand, for example. This functionality blocks user who wants to run "logs --name App" from the ExecCommand.
> 
> So I think it's best to separate them from ExecCommand

Ah, you're right. Thank you. Gonna separate them from the ExecCommand.

2021-08-23 09:13 UTC, Hazmi35 commented
> > > > > Is there a way to terminate the logs instance? Showing it's PID and using exec to run `kill <pid> -s 0` is doable, but isn't it better to implement a way to terminate it?
> > > > 
> > > > 
> > > > Yes, and that's what I'm currently thinking about.
> > > > Of course, it will use caching system to cache the spawned process. I'm thinking of these ways to end the process:
> > > > 
> > > > 1. Show its PID and then create an option named `terminate` or something.
> > > > 2. Like number 1, but with simpler custom ID instead.
> > > > 3. Create an option named `kill-all` or `terminate-all` to kill **all** the process spawned by the bot instantly.
> > > > 4. Create some options on the process spawn message using reaction or interaction collector
> > > > 
> > > > Or maybe you have any better or simpler idea?
> > > 
> > > 
> > > Come to think of it, shouldn't this be a separate command? SpawnCommand for example
> > > With that we could create something like `$spawn create <name> <shell command>` and `$spawn terminate <name>`
> > > Then, we can store the ChildProcess with the name as the key, and then we can use ChildProcess#kill to terminate it.
> > 
> > 
> > This way, it wouldn't interfere with ExecCommand, for example. This functionality blocks user who wants to run "logs --name App" from the ExecCommand.
> > So I think it's best to separate them from ExecCommand
> 
> Ah, you're right. Thank you. Gonna separate them from the ExecCommand.

Note that you don't need to create another PR, just use this one

2021-08-23 11:50 UTC, Mednoob commented
@Hazmi35 Done!

2021-08-23 12:23 UTC, Hazmi35 requested changes
We should remove the "Log" here because we can use this command other than logging

2021-08-23 12:23 UTC, Hazmi35 commented on src/commands/developers/SpawnCommand.ts
> +                    void message.channel.send("**Log process spawned**");
```suggestion
                    void message.channel.send(`**Process ${name} spawned**`);
```

2021-08-23 12:23 UTC, Hazmi35 commented on src/commands/developers/SpawnCommand.ts
> +                    void message.channel.send(`**Log process closed with code ${code!}, signal ${signal!}**`);
```suggestion
                    void message.channel.send(`**Process ${name} closed with code ${code!}, signal ${signal!}**`);
```

2021-08-23 12:23 UTC, Hazmi35 commented on src/commands/developers/SpawnCommand.ts
> +                    void message.channel.send(`**An error occured on the log process**\n\`\`\`${err.message}\`\`\``);
```suggestion
                    void message.channel.send(`**An error occured on the process ${name}: **\n\`\`\`${err.message}\`\`\``);
```

2021-08-23 13:21 UTC, Hazmi35 approved these changes
Well, you made it. LGTM.

Thanks for your contribution 🎉

2021-08-23 13:21 UTC, merged